name: Flutter Android CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    # ১. কোড চেকআউট
    - uses: actions/checkout@v4
    
    # ২. Fl SDK সেটআপ
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'  # আপনার Flutter ভার্সন দিন
        channel: 'stable'
    
    # ৩. JDK সেটআপ
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # ৪. local.properties ফাইল তৈরি (Flutter SDK পাথ সহ)
    - name: Setup local.properties
      working-directory: ./android
      run: |
        echo "Creating local.properties with Flutter SDK path..."
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "flutter.sdk=${{ github.workspace }}/flutter" >> local.properties
        echo "ndk.dir=$ANDROID_HOME/ndk/25.1.8937393" >> local.properties
        echo "Generated local.properties content:"
        cat local.properties
    
    # ৫. গ্রাডল র‍্যাপার সেটআপ
    - name: Setup Gradle Wrapper
      working-directory: ./android
      run: |
        [ -f "gradlew" ] || gradle wrapper --gradle-version 8.4
        chmod +x gradlew
        ./gradlew --version
    
    # ৬. Flutter dependencies ইনস্টল
    - name: Get Flutter packages
      run: flutter pub get
    
    # ৭. Android বিল্ড
    - name: Build APK
      working-directory: ./android
      run: |
        ./gradlew assembleDebug --stacktrace --info
    
    # ৮. APK আপলোড
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
