name: Flutter Android Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      FLUTTER_HOME: ${{ github.workspace }}/flutter
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
    # 1. কোড চেকআউট
    - uses: actions/checkout@v4
      with:
        submodules: recursive  # Flutter submodules সহ চেকআউট

    # 2. Flutter সেটআপ
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: 'stable'

    # 3. Android SDK সেটআপ
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # 4. JDK সেটআপ
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 5. Flutter পাথ সেটআপ
    - name: Configure Flutter Path
      run: |
        echo "FLUTTER_ROOT=$FLUTTER_HOME" >> $GITHUB_ENV
        echo "$FLUTTER_HOME/bin" >> $GITHUB_PATH

    # 6. local.properties ফাইল তৈরি
    - name: Create local.properties
      working-directory: ./android
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "flutter.sdk=$FLUTTER_HOME" >> local.properties
        echo "ndk.dir=$ANDROID_HOME/ndk/25.1.8937393" >> local.properties
        cat local.properties

    # 7. Flutter dependencies ইনস্টল
    - name: Get Flutter packages
      run: |
        flutter pub get
        flutter precache --android

    # 8. গ্রাডল র‍্যাপার সেটআপ
    - name: Setup Gradle
      working-directory: ./android
      run: |
        ./gradlew wrapper --gradle-version 8.4
        chmod +x gradlew

    # 9. Flutter build অপ্টিমাইজেশন
    - name: Run Flutter build
      run: |
        flutter build apk --debug --verbose
        ls -la build/app/outputs/flutter-apk/

    # 10. APK আপলোড
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: build/app/outputs/flutter-apk/app-debug.apk
        if-no-files-found: error
