name: Android CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    # ১. কোড চেকআউট
    - uses: actions/checkout@v4
    
    # ২. Android SDK সেটআপ
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: '25.1.8937393'
        cmake-version: '3.22.1'
    
    # ৩. JDK সেটআপ
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # ৪. local.properties ফাইল তৈরি
    - name: Create local.properties
      working-directory: ./android
      run: |
        echo "Creating local.properties..."
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "ndk.dir=$ANDROID_HOME/ndk/25.1.8937393" >> local.properties
        echo "Created local.properties with following content:"
        cat local.properties
    
    # ৫. গ্রাডল র‍্যাপার ইনিশিয়ালাইজেশন
    - name: Initialize Gradle Wrapper
      working-directory: ./android
      run: |
        # গ্রাডল র‍্যাপার ফাইল চেক
        if [ ! -f "gradlew" ] || [ ! -d "gradle/wrapper" ]; then
          echo "Generating Gradle wrapper..."
          gradle wrapper --gradle-version 8.4 --distribution-type bin
          
          # পারমিশন সেট
          chmod +x gradlew
          chmod +x gradlew.bat
        else
          echo "Gradle wrapper already exists"
        fi
        
        # ভার্সন চেক
        ./gradlew --version
    
    # ৬. অ্যাপ বিল্ড
    - name: Build APK
      working-directory: ./android
      run: |
        ./gradlew assembleDebug --stacktrace --info
    
    # ৭. APK আপলোড
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
        retention-days: 5
