name: Flutter Android Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: '3.22.1'  # Dart 3.5.0+ সমর্থন করে

    steps:
    - uses: actions/checkout@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Verify Versions
      run: |
        flutter --version
        dart --version
        flutter doctor -v

    - name: Get Dependencies
      run: |
        flutter pub upgrade
        flutter pub get

    - name: Build APK
      run: flutter build apk --release
