name: Enhanced Build Pipeline

on:
  push:
    tags:
      - 'v*'

env:
  FLUTTER_VERSION: '3.22.1'
  NDK_VERSION: '25.1.8937393'
  IS_STABLE: ${{ !contains(github.ref, '-') }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
            arch: x64
          - platform: linux
            os: ubuntu-latest
            arch: x64
          - platform: macos
            os: macos-13
            arch: arm64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            $FLUTTER_HOME/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Setup Android SDK
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v3

      - name: Setup NDK
        if: matrix.platform == 'android'
        uses: android-actions/setup-ndk@v2
        with:
          ndk-version: ${{ env.NDK_VERSION }}

      - name: Configure Android Signing
        if: matrix.platform == 'android'
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/keystore.jks
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=$FLUTTER_HOME" >> android/local.properties
          echo "ndk.dir=$ANDROID_HOME/ndk/${{ env.NDK_VERSION }}" >> android/local.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/local.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/local.properties

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: |
          if [ "${{ matrix.platform }}" == "android" ]; then
            flutter build apk --release
          elif [ "${{ matrix.platform }}" == "windows" ]; then
            flutter build windows --release
          elif [ "${{ matrix.platform }}" == "macos" ]; then
            flutter build macos --release
          else
            flutter build linux --release
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.platform }}-${{ matrix.arch || 'default' }}
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/windows/runner/Release/
            build/linux/x64/release/bundle/
            build/macos/Build/Products/Release/
          if-no-files-found: error
